if(NOT DEFINED DEMO OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "DEMO and WORK_DIR are required")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")

function(run_demo)
  execute_process(COMMAND "${DEMO}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Demo failed: ${ARGN}\n${output}\n${errors}")
  endif()
endfunction()

function(reject_demo)
  execute_process(COMMAND "${DEMO}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  if(result EQUAL 0)
    message(FATAL_ERROR "Demo accepted invalid arguments: ${ARGN}")
  endif()
endfunction()

run_demo(--steps 12 --seed 127 --checkpoint "${WORK_DIR}/full.pt"
  --report "${WORK_DIR}/full.json")
run_demo(--steps 5 --seed 127 --save-every 2 --checkpoint "${WORK_DIR}/split/model.pt")
run_demo(--resume "${WORK_DIR}/split/model.pt" --steps 7
  --checkpoint "${WORK_DIR}/split/model.pt" --report "${WORK_DIR}/resumed.json")
run_demo(--resume "${WORK_DIR}/split/model.pt" --evaluate-only --report "${WORK_DIR}/evaluated.json")
file(READ "${WORK_DIR}/full.json" full)
file(READ "${WORK_DIR}/resumed.json" resumed)
file(READ "${WORK_DIR}/evaluated.json" evaluated)
foreach(document IN ITEMS full resumed evaluated)
  string(JSON completed GET "${${document}}" completed_steps)
  if(NOT completed EQUAL 12)
    message(FATAL_ERROR "Wrong completed step count in ${document}: ${completed}")
  endif()
  string(JSON final_${document} GET "${${document}}" final)
endforeach()
if(NOT final_full STREQUAL final_resumed OR NOT final_full STREQUAL final_evaluated)
  message(FATAL_ERROR "Resumed/evaluation-only reports must equal uninterrupted CPU training")
endif()
string(JSON resumed_initial GET "${resumed}" initial_steps)
string(JSON evaluated_initial GET "${evaluated}" initial_steps)
if(NOT resumed_initial EQUAL 5 OR NOT evaluated_initial EQUAL 12)
  message(FATAL_ERROR "Resume/evaluation did not preserve progress")
endif()
file(SHA256 "${WORK_DIR}/split/model.pt" before)
reject_demo(--resume "${WORK_DIR}/split/model.pt" --seed 42 --steps 1)
reject_demo(--resume "${WORK_DIR}/split/model.pt" --evaluate-only --steps 1)
reject_demo(--resume "${WORK_DIR}/split/model.pt" --evaluate-only
  --report "${WORK_DIR}/split/model.pt")
reject_demo(--steps 1 --steps 2)
file(SHA256 "${WORK_DIR}/split/model.pt" after)
if(NOT before STREQUAL after)
  message(FATAL_ERROR "Invalid command altered the input checkpoint")
endif()
# Windows-backed Docker mounts may resolve differently cased names to one file.
file(WRITE "${WORK_DIR}/case-probe" "probe")
if(EXISTS "${WORK_DIR}/CASE-PROBE")
  # Use distinct fresh names on every test run to exercise the post-save check.
  string(RANDOM LENGTH 12 ALPHABET abcdef0123456789 case_id)
  reject_demo(--steps 1 --checkpoint "${WORK_DIR}/case-${case_id}.pt"
    --report "${WORK_DIR}/CASE-${case_id}.PT")
  if(EXISTS "${WORK_DIR}/case-${case_id}.pt")
    run_demo(--resume "${WORK_DIR}/case-${case_id}.pt" --evaluate-only)
  endif()
endif()
message(STATUS "Demo workflow: uninterrupted = resumed = evaluation-only; invalid requests preserve checkpoint")
